{{- if empty .Values.cloudConfig.externalSecret -}}
{{- $_ := .Values.cloudConfig.token | required "Secret creation requires the token to be defined" -}}
{{- $_ = .Values.cloudConfig.datacenters | required "Secret creations requires at least one datacenter to be defined" -}}
{{- if .Values.cloudConfig.datacenters | len | eq 0 -}}{{ fail "Secret requires at least one datacenter to be defined" }}{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ionoscloud-ccm.name" . }}-cloud-config
  labels:
    {{- include "ionoscloud-ccm.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $dc := .Values.cloudConfig.datacenters }}
  {{ $dc }}: {{ include "ionoscloud-ccm.cloudConfigContent" $ | b64enc }}
{{- end }}
{{- end }}
